#! /bin/bash
if [[ $USER = "wjoel" ]]; then
  python setup.py build && cp build/lib.linux-x86_64-2.7/c_module.so .
else
  python setup.py build && cp build/lib.macosx-10.6-universal-2.6/c_module.so . && python jonatans_lattice_test.py
fi